version: '3'

services:
    reddit-bot:
        container_name: reddit-bot
        build:
            context: .
            dockerfile: Dockerfile
        #        environment:
        volumes:
            - /home/agro/gh/qsf-paywalls/config.js:/app/config.js
        command: 'npm run start'
        networks:
            - reddit-bot-compose-network

networks:
    reddit-bot-compose-network:
        driver: bridge
