version: '3'

services:
    reddit-bot:
        container_name: reddit-bot
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./.env
        environment:
            - USER_AGENT=$USER_AGENT
            - CLIENT_ID=$CLIENT_ID
            - CLIENT_SECRET=$CLIENT_SECRET
            - USERNAME=$USERNAME
            - PASSWORD=$PASSWORD
        command: 'npm run start'
        networks:
            - reddit-bot-compose-network

networks:
    reddit-bot-compose-network:
        driver: bridge
